openapi: 3.0.0
info:
  title: Webhooks
  version: '1.0'
  contact:
    name: ReCharge
    url: rechargepayments.com
  termsOfService: 'https://rechargepayments.com/terms-of-service/'
  description: |

    Webhooks notify you about events happening within ReCharge. They can feed data into your client-side application that you can use to take action. Webhooks deliver data about events like customers adding an item to cart, subscription cancellations and other specific events in real-time. 

    ## Uses

    You can use webhooks to collect data from our API and create a variety of custom solutions. For example, you can build custom dashboards that use webhook callback data to show information about customer purchases. Data from webhook callbacks can be used to create analytics reports store owners can use to improve the shopping experience. Your application can be reactive to ReCharge's webhooks and take follow up actions like updating a subscription product when customers add it to cart.

    Here is an example workflow:

    If you offer a subscription where the product a customer receives should changeb every month, your application can listen for the `order/created` callback and when it receives it, make a REST API call to change the product belonging to that subscription.

    ## Handling the callback request

    Callback payloads are identical to ReCharge's REST API payloads. For example, the callback for the `subscription/created` webhook will be identical to the payload of a `GET` request to the `subscriptions/<subscription_id>` endpoint.

    You should acknowledge you've received ReCharge's webhook callback by sending a `200 OK` response. If ReCharge doesn't receive a response, or receives any response outside of the `200` range, ReCharge will act as though you did not receive the callback. Our server waits 5 seconds for a response. If we do not receive a response in that time period we consider the request failed. Our system will attempt to send the same webhook 20 times over a period of 48 hours (or two days). If the request fails each time our within this timeframe, we will delete this webhook from our system. At present we also log these deleted webhooks in our system.

    <br>

    <!-- theme: warning -->
    > ### Retries
    > Due to webhook retries, itâ€™s possible that your application will receive the same webhook more than once. Ensure idempotency of the webhook call by detecting such duplicates within your application.
servers:
  - url: 'https://api.rechargeapps.com'
paths:
  /webhooks:
    get:
      summary: Retrieve all webhooks
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/get-hooks.v1.yaml
              examples:
                Example:
                  value:
                    webhooks:
                      - address: 'https://request.in/foo'
                        id: 19451
                        topic: subscription/created
                      - address: 'https://request.in/foo'
                        id: 19453
                        topic: subscription/cancelled
      operationId: get-webhooks
      description: Retrieve all available webhooks.
    post:
      summary: Create a webhook
      operationId: post-webhooks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook:
                    $ref: ../models/webhook-response.v1.yaml
              examples:
                Example:
                  value:
                    webhook:
                      address: 'https://request.in/foo'
                      id: 6
                      topic: subscription/created
      description: Create a webhook.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/base-webhook.v1.yaml
            examples:
              Example:
                value:
                  address: 'https://request.in/foo'
                  topic: subscription/created
  '/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Retrieve webhook
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  webhook:
                    $ref: ../models/webhook-response.v1.yaml
              examples:
                Example:
                  value:
                    webhook:
                      address: 'https://request.in/foo'
                      id: 6
                      topic: subscription/created
      operationId: get-id
      description: Retrieve a webhook.
    put:
      summary: Update webhook
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/webhook-response.v1.yaml
              examples:
                Example:
                  value:
                    webhook:
                      address: 'https://request.in/foo'
                      id: 6
                      topic: subscription/created
      operationId: put-id
      description: Update a webhook.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                topic:
                  type: string
            examples:
              Example:
                value:
                  address: 'https://request.in/foo'
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
    delete:
      summary: Delete webhook
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-id
      description: Delete a webhook.
components:
  schemas: {}
  securitySchemes: {}
